# environment.yml
name: ml-wsl-base
channels:
  - conda-forge
dependencies:
  # --- Core Libraries (Data Science Foundation) ---
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - tqdm
  - jupyterlab
  - optuna
  - xgboost
  - lightgbm

  # --- Configuration & Utilities ---
  - omegaconf
  - hydra-core
  - pyyaml
  - rich
  - click

  # --- ML Tracking & Monitoring ---
  - mlflow
  - tensorboard

  # --- Tools (Installed via Pip) ---
  - pip
  - pip:
    - pre-commit
    - ruff
    - pytest
    - pytest-cov
    - pytest-xdist
    - isort
