# =============================================================================
# PROJECT CONFIGURATION
# =============================================================================
project:
  name: "ml-wsl-boilerplate"
  version: "0.1.0"
  description: "Modern ML project template"
  author: "Daniel"

# =============================================================================
# DATA CONFIGURATION
# =============================================================================
data:
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  features_dir: "data/features"
  
  # Data processing settings
  train_test_split: 0.8
  validation_split: 0.1
  random_state: 42
  
  # Data cleaning
  drop_duplicates: true
  missing_value_strategy: "mean"  # mean, median, mode, drop
  
  # Feature engineering
  scale_features: true
  feature_selection: false
  max_features: null

# =============================================================================
# MODEL CONFIGURATION
# =============================================================================
model:
  type: "xgboost"  # xgboost, lightgbm, sklearn, neural_network
  
  # XGBoost specific parameters
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    n_jobs: -1
    
  # LightGBM parameters
  lightgbm:
    n_estimators: 100
    max_depth: -1
    learning_rate: 0.1
    num_leaves: 31
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    n_jobs: -1
    
  # Scikit-learn RandomForest
  sklearn:
    n_estimators: 100
    max_depth: null
    random_state: 42
    n_jobs: -1

# =============================================================================
# TRAINING CONFIGURATION
# =============================================================================
training:
  # Cross-validation
  cv_folds: 5
  cv_strategy: "stratified"  # kfold, stratified, group
  
  # Hyperparameter optimization
  hyperopt:
    enabled: false
    n_trials: 100
    timeout: 3600  # seconds
    
  # Early stopping
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001
    
  # Metrics to track
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "roc_auc"

# =============================================================================
# MLFLOW / EXPERIMENT TRACKING
# =============================================================================
mlflow:
  enabled: true
  tracking_uri: "file:./mlruns"
  experiment_name: "ml-wsl-boilerplate"
  
  # What to log
  log_params: true
  log_metrics: true
  log_model: true
  log_artifacts: true
  
  # Model registry
  model_registry:
    enabled: true
    model_name: "ml-wsl-model"

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # File logging
  file_logging:
    enabled: true
    log_dir: "logs"
    max_file_size: "10MB"
    backup_count: 5
    
  # Console logging with Rich
  console_logging:
    enabled: true
    rich_formatting: true
    show_time: true
    show_path: false

# =============================================================================
# PATHS AND DIRECTORIES
# =============================================================================
paths:
  data_dir: "data"
  models_dir: "models"
  logs_dir: "logs"
  notebooks_dir: "notebooks"
  config_dir: "config"
  
  # Output directories
  outputs_dir: "outputs"
  figures_dir: "outputs/figures"
  reports_dir: "outputs/reports"

# =============================================================================
# ENVIRONMENT SETTINGS
# =============================================================================
environment:
  seed: 42
  n_jobs: -1
  gpu_enabled: false
  memory_limit: "8GB"
  
  # Jupyter settings
  jupyter:
    autoreload: true
    inline_plots: true
    plot_backend: "matplotlib"
    figure_size: [10, 6]